### ISSUE TITLE
Create .Rmd sample file with our favorite chunk options

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#102]
...with explanations, such as:

difference between putting something in the code chunk header vs. setting it for all chunks with `knitr::opts_chunk$set()`:

```{r setup, include=FALSE, cache=FALSE}
options(digits = 3, scipen = 999)
knitr::opts_chunk$set(fig.align='center',
               cache=TRUE, message = FALSE, 
               warning = FALSE, echo = FALSE)
```

using `fig.height` `fig.width` `fig.asp` `fig.align`

**Comment by zachbogart** [comment]
Referenced in R Basics: https://edav.info/basics.html#communicating-results

Direct Link: https://github.com/jtr13/EDAV/blob/master/data/chunk_option_showcase.Rmd
