### ISSUE TITLE
Check links across site

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#109]
This would be very helpful to confirm the structure of the site.

Check all links and report if anything is:
- broken (leads to 404)

More subtle:
- links to pages on edav.info should **not** open in a new tab
- links to any external pages should **always** open in a new tab
- Some images/hover situations have alt-text. check that these are present/relevant and propose changes as needed

**Comment by TimKartawijaya** [comment]
Hi Zach,
Can I work on this issue for my contribution? I'll write up a short report indicating the dead links and the subtle errors, then I'll work on fixing them through a pull request.

**Comment by zachbogart** [comment]
Much appreciated. I would check with Joyce and confirm it satisfies the community contribution.

**Comment by TimKartawijaya** [comment]
Thanks! I'll check with her. If not, I'll do an additional issue to satisfy the requirement.

**Comment by TimKartawijaya** [comment]
Hey Zach, Dr. Robbins said this issue should satisfy the requirement, so I can take on this issue. How do I label this issue to have the "student helping" tag?

**Comment by zachbogart** [comment]
It is on the sidebar "Labels". Click on the gear and scroll down.

**Comment by TimKartawijaya** [comment]
I think I'm not able to do so since I'm not an owner of the repository. Thanks for all the updates so far!
