### ISSUE TITLE
Submit a resource link to something that bugs you

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#110]
Often students take getting help into their own hands and solve the problem themselves. If you have come across a resource that helped you get setup with R or another basic tutorial, propose it as a link we could add. It would benefit future students immensely.

**Comment by nehasaraf1994** [comment]
Hi Zach,
Can I take up Ridgeline plots for a page in EDAV.info?

**Comment by zachbogart** [comment]
Sure. Submit an issue outlining your intentions and we can go from there.

**Comment by nehasaraf1994** [comment]
Created an Issue.
