### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by kalendar** [jtr13/EDAV#111]
Thanks for this incredible resource!

In the book you encourage people to clone the repo, make changes, and submit pull requests. Yet these kinds of activities explicitly prohibited by the ND license you've chosen the book. The purpose of the ND condition is specifically to prohibit people from distributing substantive changes to a work. I'd encourage you to drop the ND condition from your license so that people will feel safe contributing.

**Comment by jtr13** [comment]
Thank you for shedding light on this very important issue.  We do not want to make it difficult for people to contribute; we do want to prevent distributing all or parts of the material without attribution.  Is there a specific license that you would recommend?

**Comment by zachbogart** [comment]
Maybe this will make more sense: https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by kalendar** [comment]
If you want to prevent distributing all or parts of the material without attribution, the CC BY license does this (https://creativecommons.org/licenses/by/4.0/). If you want everyone who makes changes to your book to be required to both (1) attribute you and (2) license their changes under the same license as yours, the CC BY-SA license does this (https://creativecommons.org/licenses/by-sa/4.0/).

I hadn't noticed the issue with r4ds - I'll bring it up with Hadley.

And thanks again for your work on this resource. It's great!

**Comment by jtr13** [comment]
That's very helpful, thanks! @zachbogart: let's discuss

**Comment by zachbogart** [comment]
@kalendar what would you recommend regarding the non-commercial designation? I notice both licenses you recommend are designated Free Cultural Works (https://creativecommons.org/share-your-work/public-domain/freeworks). Do you think the non-commercial designation is too restrictive for an educational resource?

**Comment by kalendar** [comment]
Personally, I believe it is too restrictive, yes. This is because there are no clear guidelines around what is and isn't commercial. For example, the community disagrees about the answers to the following questions:

- Can I use an NC licensed resources in a university class, where students have to pay tuition to attend? (Some say yes, some say no - because money is involved.)
- Can I take an NC licensed resource to a copy shop and have them print a copy for me? (Some say yes, some say no - because money is involved.)

The ambiguity about what one can and can't do with an NC licensed resource chills usage of the resource. So if your primary concern is getting the resource used by lots of people, I would avoid NC. If your primary concern is making sure there's no possibility of others making money from your work (for a broad range of what "making money from your work" might mean), then you should use a license with the NC condition.

Does that make sense?

**Comment by zachbogart** [comment]
Yes it does. Thank you for the clarification.
