### ISSUE TITLE
Add parallel coordinate plots

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#112]

**Comment by aashnakanuga** [comment]
Hi, I would like to help contribute to this issue for my community contribution. Would the information we need to add follow a similar pattern as the pages about other plots? And are there any specific examples or information that need to be added?

**Comment by zachbogart** [comment]
Good to hear! 

I would follow an outline similar to the one for other green chart pages (tl;dr, theory, simple examples, etc.)

You can clone the repo and use the chapter_template.Rmd file asa starting point. Come to my office hours if you have questions.

**Comment by aashnakanuga** [comment]
Okay, I will do that! Thanks

**Comment by aashnakanuga** [comment]
Hi Zach,
So I have come up with a basic layout as follows:
1. tl;dr - Using the "diamonds" dataset (there are many ways to show a lot of information, I would love to discuss that with you during office hours once about which visualization I should go for)
2. Simple example - Using the "iris" dataset, just a basic plot with clusters on the "Species" column
3. Theory - A link to our textbook chapter 6
4. When to use - Multivariate continuous data, to identify trends for different clusters, and sometimes also with time series data and indices
5. Considerations - When to use clustering, alphaLines, what scales to use, what order of variables to use
6. Modifications - flipping the coordinates, clustering, highlighting trends, using splines, adding boxplots to the graph
7. External resources - other helpful links for Parallel coordinate plots

Please let me know if this is okay, and if I should add/remove anything. I will come see you during office hours and discuss the content once. Thanks!

**Comment by zachbogart** [comment]
Looks very good. Looking forward to see it as it develops!

**Comment by aashnakanuga** [comment]
Hi Zach
I pushed the Rmd file to my forked repo and initiated a pull request, but there was an error. It is some issue with installing the "statebins" library. The message reads:
 "The command "Rscript -e 'devtools::install_github(c("hrbrmstr/statebins"), build_vignettes = FALSE)'" failed and exited with 1 during ."
I don't know what is causing this error, because as far as I am aware my code should not conflict with anything related to this library! Please let me know how to proceed.

**Comment by zachbogart** [comment]
I will look into it. Travis hits a rate limit from time to time, so it may not be on our end.

**Comment by aashnakanuga** [comment]
Hi Zach, are there any updates? Is there anything I can do for resolving the issue?

**Comment by zachbogart** [comment]
#176
