### ISSUE TITLE
Add mosaic plots

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#113]
See: https://github.com/jtr13/codehelp/blob/master/R/mosaic.md

**Comment by harin** [comment]
@jtr13 @zachbogart Can I help with this issue for my community contribution? Also since there are already many examples in the link above, what else do you want me to add to the mosaic plot page?

**Comment by zachbogart** [comment]
Yes you may! We would like you to flesh out the work provided and follow an outline similar to the one shown in the other green chart chapters. There is a chapter_template you can copy to get yourself started. Also, feel free to stop by my office hours on Thursdays to chat about it.

**Comment by harin** [comment]
@zachbogart Thanks, I'll take this issue then.

**Comment by jtr13** [comment]
Hi, It's completely fine to borrow from anything you find of mine including the material posted on CourseWorks since I'm an author of edav.info, no need to give additional credit.  Thanks for checking!

**Comment by zachbogart** [comment]
🎉 https://edav.info/mosaic.html
