### ISSUE TITLE
Add heatmaps

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#114]
Heatmaps should be moved from scatterplots into its own chapter.

**Comment by zachbogart** [comment]
- Created a work in progress banner as well as a template for pages that are under construction.
- Moved heatmap content to it's own chapter. Currently in progress; needs a fancy example of a heatmap. Open to ideas!

- Template: https://github.com/jtr13/EDAV/blob/master/chapter_template.Rmd
- Heatmap: https://edav.info/heatmap.html

**Comment by jtr13** [comment]
Add additional examples from heatmaps.html (so far we just have 2d bin count heatmaps

**Comment by zachbogart** [comment]
Added tl;dr example and wine dataframe heatmap example.

https://edav.info/heatmap.html
https://github.com/jtr13/EDAV/pull/127

**Comment by zachbogart** [comment]
Is this good to close?

**Comment by jtr13** [comment]
Yes. (I have a few things to tweak at some point... but the issue doesn't need to stay open for that.)
