### ISSUE TITLE
Add time series

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#115]

**Comment by my2582** [comment]
May I take this issue as my contributions? I am (well, was, one and a half months ago) to R, but I worked with time-series data for many years. So I guess I might bring some practical perspectives here.

**Comment by zachbogart** [comment]
Sure thing! I would recommend starting with the chapter template we have available (https://github.com/jtr13/EDAV/blob/master/chapter_template.Rmd). You can clone the repo, copy the template to a new .Rmd file, and go to town!

Some suggestions:
- try to replicate the chart format we have for green-colored chapters already published to the resource:
      - tl;dr (fancy example of time series with code)
      - Simple examples (the simplest examples you can make possible)
      - Etc. (see published chapters)
- Similar to the final project, writing what you are coding is often much more important than the code itself. Discuss important points and common problems.
- Keep us posted! Let us know what you are working on using this issue and how it's going. Show us your code using pull requests and feel free to ask us for clarification or questions regarding github stuff or the resource's backend structure.

Please let us know if you need more clarification (the setup of the work is often much harder than the work itself). Looking forward to what you come up with.

**Comment by my2582** [comment]
Great. I'll take it then and keep you updated as I'm working on.

**Comment by my2582** [comment]
Here's my thoughts on how to organize my contribution. As you said, the problem setup was indeed hard. After giving a few simple examples to plot time-series data, what I want to focus is

  1. to choose a better way of illustrating time-series data between a line chart and bar chart, the two most frequently used charts in finance.
    1) A line chart is good at showing overall trends but it loses some precision.
    2) A bar chart is useful to complement to a line chart.
 
  2. to give industry-level examples. I will use data that professionals in finance would be interested in while choosing a topic that easy to understand.

**Comment by zachbogart** [comment]
time series work done with #208
