### ISSUE TITLE
Add faceting section

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#118]
Examples from ContinuousCategoricalCode.html in CourseWorks.

Would cover best practices for faceting, not related to a particular chart type. Things like the need to experiment with aesthetic mappings (x, y, fill) and faceting variables, and to proceed with caution when freeing x or y scales since the whole point of faceting is to be able to make comparisons with the same scales. On that note, I'm thinking that as needed we could add "not recommended" examples with explanations in the various chapters. For example, here we could show faceting with scales ="free_y" and explain why it's problematic. (I've got a good example.)

**Comment by kskaran94** [comment]
Hi, Can I help with this or any other important issue for my Community contribution ?

**Comment by zachbogart** [comment]
Every issue is an important issue! Yes, feel free to help out! @jtr13, you may want to clarify the type of chapter/section you are envisioning and @kskaran94 could look into creating it.

**Comment by zachbogart** [comment]
@kskaran94 just for my benefit, please confirm you are taking on this issue. Thanks.

**Comment by kskaran94** [comment]
Yes Zach, I will be taking this issue for community contribution

**Comment by kskaran94** [comment]
@jtr13 @zachbogart 
I have made an .Rmd with few examples of good facetting and one example of bad facetting. 
Should i generate a pull request ? I need your inputs on the this

**Comment by jtr13** [comment]
Things to include in this chapter:
* Facetting is for categorical variables, generally combined with continuous
* Facets can also be created with a binned continuous variable, for example age by decades (converting a continuous to categorical)
* Choose aesthetic mappings carefully: fill? color? facets?
* Different choices show off different features of the data
* Don't overdo it... can't put everything in one graph.
Use `SpeedSki`?
* Build graphs one variable at a time, not all at once
