### ISSUE TITLE
Travis backend halting maps chapter

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#134]
I am trying to get the maps chapter pull request (https://github.com/jtr13/EDAV/pull/132) to build. I purged the Travis CI cache and removed the bookdown remote and it seems to get to the point of executing the R code for that chapter. 

I'm now adding back in the packages necessary (`choroplethr` and `statebins`) to see if it completes.

Still unable to get it to run on my local machine due to `sf` dependency

**Comment by jtr13** [comment]
Progress.  Just realized I forgot to put choroplethrMaps in DESCRIPTION so just added it.  Are you sure we don't need the bookdown remote? 

Also, what's the problem you're having with "sf"? Might the dev version help?  See: https://github.com/r-spatial/sf/

**Comment by zachbogart** [comment]
No I'm not sure at all. I can try to add the remote back in. I'm not sure what `choroplethrMaps` adds. I tried to add it before calling `library(choroplethr)` and I still get an `sf` error.

I will merge the pull request with the tacked-on remote.

**Comment by zachbogart** [comment]
Looks like it is failing due to a package called `units`, which I think is related to `statebins`. 
https://travis-ci.org/jtr13/EDAV/builds/444895857?utm_source=github_status&utm_medium=notification

**Comment by zachbogart** [comment]
I think this problem merits solving the "Travis pull request problem". I think we may want to see if Travis can just build the book but not deploy it for a pull request so we can diagnose this without having to deploy a faulty book and hope it gets resolved and deployed by Travis after merging a PR.

I found a site that makes it seem like we could solve this: https://denysdovhan.com/building-pull-requests-using-travis/

I'm going to remove maps.Rmd from the `_bookdown.yml` and make sure everything works like normal. Then see if I can get Travis to execute for a PR but not publish it till merged.

**Comment by jtr13** [comment]
All good.  I also wonder if a different bookdown setup would solve this -- that is an alternative to the gh-pages branch approach.

**Comment by zachbogart** [comment]
I think that would work as well. But, that would involve some fiddling of the domain setup. I think there are multiple solutions.

**Comment by zachbogart** [comment]
Okay. I think I've convinced myself that it works!

It should be that a pull request will trigger Travis to build the book (run render_book) but NOT deploy the book (will not be published live to the site). Once merged to master (or if you push directly to master), Travis will be triggered and push it live to gh-pages.

I encourage you to start a new pull request and see if you can make Travis happy.

**Comment by jtr13** [comment]
Ok, will try now.
