### ISSUE TITLE
Add Cleveland dot plot and qqplot

### ISSUE THREAD

**Issue by hao871563506** [jtr13/EDAV#145]
How about adding cleveland dot plot and qqplot. Their overview, coding, advantage, and disadvantage. 
But I am afraid is not a big section, so adding them to the scatterplot section?

**Comment by zachbogart** [comment]
Good ideas! We have a Cleveland plot in the works. The qq plot would be a good addition to the scatterplot page.

**Comment by hao871563506** [comment]
> Good ideas! We have a Cleveland plot in the works. The qq plot would be a good addition to the scatterplot page.

Okay, I will work on qqplot then
