### ISSUE TITLE
Add a page on map/spatial data

### ISSUE THREAD

**Issue by tniyomkarn** [jtr13/EDAV#146]
Adding a page on plotting spatial data which focuses on state and zip code using 'choroplethr' library.
@zachbogart  Do you think this will be helpful as a community contribution?

**Comment by zachbogart** [comment]
Sounds helpful to me! You could make a walkthrough on creating a map plot if you'd like.

**Comment by AkhilPunia** [comment]
Hi @zachbogart , I am planning to write a tutorial on using leaflet library for interactive plotting of geographic data. Can this be included under this section? Is someone already working on it ?

**Comment by zachbogart** [comment]
Go ahead! I think it would be a nice addition to the maps chapter.

**Comment by AkhilPunia** [comment]
#194

**Comment by zachbogart** [comment]
Changed to #207
