### ISSUE TITLE
Add a page on diverging stacked bar chart ( Likert data)

### ISSUE THREAD

**Issue by ankitaa06** [jtr13/EDAV#147]
Hi Zach, 
Do we need the same and can I implement this as a part of my community contributions?

**Comment by zachbogart** [comment]
I would look into adding this to the bar chart chapter.

**Comment by ankitaa06** [comment]
Awesome Zach, and will this be sufficient towards my community contribution or  I should think of adding something more like diverging lollipop plot, diverging dot plot, area chat extra. I know these were not in the syllabus, but are one of the good graphs to visualize deviation.

**Comment by zachbogart** [comment]
This will satisfy your community contribution.
