### ISSUE TITLE
Add a page on handling outliers

### ISSUE THREAD

**Issue by kiransaini** [jtr13/EDAV#148]
Hi Zach,
I would like to add a page on types of outliers and how to handle them. Do we need this and can I implement this as part of my community contribution?

**Comment by zachbogart** [comment]
Fabulous idea! What did you have in mind in terms of types of outliers?

**Comment by zachbogart** [comment]
Sounds good. I would look into how to handle them visually in ggplot and how they affect results.

**Comment by zachbogart** [comment]
Go for it! Please link to the relevant PR (pull request) you generate in this issue. 

By that I mean your PR will have a number. You can link it just by typing "#__YOURNUMBER__" in this conversation thread. 

Much appreciated.

**Comment by kiransaini** [comment]
Hi Zach,
Please find the pull request generated below: #195
