### ISSUE TITLE
Add a tutorial/introduction for forcats

### ISSUE THREAD

**Issue by WhiteSpiderLily** [jtr13/EDAV#163]
Can I write a tutorial or introduction for forcats as a contribution to the community? 
We have been dealing with factors in data sets a lot. It would be beneficial to introduce forcats for working with factors. Practical functions include "fct_inorder", "fct_recode", "fct_drop", "fct_relevel", "fct_expand", "fct_rev", etc.
1. I can give a description of factor variables in r.
2. And then I will write a tutorial on how to use the functions in forcats with examples under each section.

**Comment by zachbogart** [comment]
Fabulous idea! I would love to see a walkthrough on forcats (red page).

**Comment by jtr13** [comment]
We're working on cleaning things up for the new semester so I will close this issue now. However at any point please feel free to open it up again or submit a PR.
