### ISSUE TITLE
EDAV2Notes.md :  page number for Javascript portion

### ISSUE THREAD

**Issue by anipin** [jtr13/EDAV#17]
The page numbers for JavaScript portion of the textbook is 36-52, in the slide it is mentioned 52-61. Not a technical issue, but just thought will bring to your notice 
Saw the same in the first lecture of D3 too (3/8)

**Comment by jtr13** [comment]
Thanks! Can you submit a pull request to fix it? :-)

**Comment by jtr13** [comment]
I merged the pull request. If there are other places where you think it would be helpful to reference the text, feel free to add in the same format: _IDVW_, p. xx. Thanks!
