### ISSUE TITLE
Multiple independent plots in one window

### ISSUE THREAD

**Issue by eaishwa** [jtr13/EDAV#172]
Hi Zach,

I am planning to create a page to explain how to create multiple plots in one window so that it is easy to compare them. To be precise, we may be interested in seeing histograms with different binwidths. It would be helpful to have them on the same window. Does this sound like a good one for community contribution?

**Comment by zachbogart** [comment]
Sounds like a fine contribution. Look forward to what you come up with.

**Comment by jtr13** [comment]
We're working on cleaning things up for the new semester so I will close this issue now. However at any point please feel free to open it up again or submit a PR.
