### ISSUE TITLE
Read data with various formats from different resources

### ISSUE THREAD

**Issue by ZhangZhida** [jtr13/EDAV#175]
Hi Zach,

I think reading various data is an interesting topic. Since the data can have different formats and from various places, maybe I can write a documentation page on how to read input data. 

The points I am going to cover include,
    - Read built-in R dataset. Those datasets include mtcars, iris, etc, and I will give a list of datasets we can play with;
    - Read local files. We can read files on local machine like CSV, TXT;
    - Read web data. We can access a URL to get data from the web;
    - Read database table. We connect to the database management system like Microsoft Access and MySQL, fetch the table we want, make the SQL queries, and then close the connection;
    - Read JSON/XML/HTML file. We can read those Markup Language style file using r packages;
    - More resources on how to read input data.

What do you think of that?

**Comment by zachbogart** [comment]
Sounds like an excellent idea!

**Comment by ZhangZhida** [comment]
Great! I will try as best as I can. And, can that count as community contribution?

**Comment by zachbogart** [comment]
#188
