### ISSUE TITLE
More General Resources

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#205]
We have amassed a great collection of chapters on charts from the first round of students to work with edav.info/. I think a great addition would be to add general link to books/cheatsheets/etc. to the general resources chapter. **Especially articles!** It's always nice to have a good collection of resources in one place.

Specifically, I'm thinking about general resources concerning EDAV/R/dataviz/similar topics. Include the link to the resource (follow similar link formatting) and a quick blurb on the link's usefulness.

If you are interested, please open up a **separate issue** and reference this one in the conversation.

**Comment by jtr13** [comment]
Closing some old issues.  Will open a new one to move General Resources into specific chapters.
