### ISSUE TITLE
EDAV8Notes.md -> missing append("path") in Step 2

### ISSUE THREAD

**Issue by anipin** [jtr13/EDAV#31]
Dear Professor, 

I was trying to follow the steps in EDAV8Notes.md for line charts, In Step 2, there is a missing "append" logic  in the chain .

```
 d3.select("svg").append("path").datum(dataset)
    .attr("d", mylinegen)
    .attr("fill", "none")
    .attr("stroke", "teal")
    .attr("stroke-width", "5");
```

Also, in the style section below, the classname should be "linestyle"

 The associated *.html is fine.

**Comment by jtr13** [comment]
Fixed, thank you!
