### ISSUE TITLE
Look into a domain name

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#42]
- [Google domains](https://domains.google/) is the easiest
- edav.info for $12/year

**Comment by zachbogart** [comment]
Could also look into a [Columbia URL](https://cuit.columbia.edu/columbia-domain-names) or one for a [Columbia Student Group](https://studentgroups.columbia.edu/#/cu_card_group-50)

**Comment by jtr13** [comment]
I purchased edav.info... what's next?

**Comment by jtr13** [comment]
I started following these instructions to set it up: http://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#custom_domains It wasn't working so I tried to revert everything I had done but it is still stuck on edav.info and I got to go... sorry!

**Comment by zachbogart** [comment]
You need to setup a connection on the Google Domains side as well. These two articles should help:

- https://medium.com/@Tnylnc/tnylnc-how-to-set-up-github-pages-with-google-domains-83bd5a4fbc5c
- https://medium.com/@jeauxcal/so-you-bought-a-google-domain-name-now-what-5fd72dffe370

**Comment by jtr13** [comment]
Thanks, it's working now! Would it be cool or dumb to change the name "EDAV Resource" to "EDAV.info"? (Either way, "EDAV Resource" should be superseded...)

**Comment by zachbogart** [comment]
Up and running as edav.info/

:)

We could chat next week, but currently some versions of the URL people may type will **not** work:
  - anything with "www." (www.edav.info, http://www.edav.info): will say the site cannot be reached
  - anything with https (https://edav.info, https://www.edav.info): will complain the connection is not private

These cases can be solved by setting up a free Cloudflare account for the site. Not a big deal, but worth considering to cover those corner cases.

**Comment by jtr13** [comment]
Ok, to be discussed. Based on the first article you sent, I thought that could be addressed by adding those URL versions to CNAME -- they put both example.com and www.example.com in CNAME -- but no such luck.

**Comment by jtr13** [comment]
Any reason not to close this?

**Comment by zachbogart** [comment]
I'd say we're done. Maybe Cloudflare discussion later in the week.
