### ISSUE TITLE
Custom 404 Page

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#44]
Along with Cloudflare, it would help smooth out corner cases. Am finding it difficult to solve, though.

**Comment by zachbogart** [comment]
Finished. http://edav.info/djkshflksdhf

**Comment by jtr13** [comment]
Very cute. When you get a chance, can you add instructions on how you did this in the "how this book was made" section?

**Comment by zachbogart** [comment]
Will do.
