### ISSUE TITLE
Add Syllabus Page

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#45]
Add copy of syllabus as a chapter to the site

**Comment by zachbogart** [comment]
I added a syllabus template to your drafts folder (joyce_drafts/01b-syllabus.Rmd) to build off of.

**Comment by jtr13** [comment]
Thanks.  I will keep the syllabus in CourseWorks though.  The principle is that anything with dates will stay in CourseWorks so that edav.info doesn't _have_ to be updated every semester.
