### ISSUE TITLE
MEETING: Travis CI

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#51]
I've been writing up ideas for the contribute page and finding that:

- having students contribute their own pages and updates sounds awesome
- it could easily get out of hand

I think it would be wise to create a Travis CI account for edav.info/ so that people (including you and I) only ever touch the .Rmd files. Then, Travis CI can build the site for us and we don't have to teach people about rendering or decide how we want to handle all that.

It looks kinds complicated to setup, but it should help out immensely in the long-run.

Some info about it here:
https://bookdown.org/yihui/bookdown/github.html

**Comment by zachbogart** [comment]
Some links:

- https://github.com/rstudio/bookdown-demo/blob/master/_deploy.sh
- https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo
- https://bookdown.org/yihui/bookdown/github.html

**Comment by jtr13** [comment]
All good... let's discuss

**Comment by zachbogart** [comment]
Success! Travis is up and running. Just be sure to leave gh-pages alone and we should be good.

:)

Closing...
