### ISSUE TITLE
Transfer to a Team Organization

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#63]
maybe consider creating this project as a team

https://help.github.com/articles/organizing-members-into-teams/

**Comment by jtr13** [comment]
I've used organizations in the past and found it more complicated.  is there a specific advantage you had in mind?

**Comment by zachbogart** [comment]
None at all, really. :)

I was going through all the tabs of the GitHub and making sure everything looked good (adding templates and such) and it was one of the things you can do. But it could very well be more hassle than it's worth.

Probably trash it?

**Comment by jtr13** [comment]
Yeah... I would say so unless we find some functionality that we don't have now.  Appreciate the thoroughness of your approach though!

**Comment by zachbogart** [comment]
Removed the organization.
