### ISSUE TITLE
Add material on setting up Travis to how was this book made

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#68]
I put together some notes here: https://jtr13.github.io/travis-howto/

(Also here https://github.com/jtr13/EDAV/blob/master/joyce_drafts/WebPublishingNotes.Rmd but the former is slightly more expanded)

Why does it look so easy? It was not. 😫

**Comment by jtr13** [comment]
Btw, when I opened this issue, I got this following popup:
![screenshot 2018-07-22 08 44 56](https://user-images.githubusercontent.com/14161912/43045737-5d7ddf8c-8d8c-11e8-98eb-02c8d4a15eb0.png)

Nicely done. :clap:

**Comment by zachbogart** [comment]
Glad you like the popup. Was wondering how people would see that stuff if they weren't in the know.

**Comment by zachbogart** [comment]
Added your material on Travis: http://edav.info/publish.html

Related pull request: https://github.com/jtr13/EDAV/pull/70

Closing...
