### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#74]
Not sure if you are interested, but you can get info on which pages of the site people are viewing, which could help inform us what pages are most important/should be expanded.

[This book](https://benmarwick.github.io/bookdown-ort/mods.html#google-analytics) discusses the very simple setup. It's basically a question of whether you want to include it or not.

**Comment by jtr13** [comment]
Let's discuss...

**Comment by zachbogart** [comment]
Will probably never look at it. Not worth the trouble.

Closing...
