### ISSUE TITLE
bookdown contest

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#80]
-template for course resources
-saves time in class
-everything in one place, that doesn't need to be moved every semester
-includes info on how to to create it 
-collaborative, at any level, with clear instructions on how to contribute
see https://zachbogart.com/bookdown-template/

**Comment by zachbogart** [comment]
So the bookdown contest deadline of October 1st is fast approaching. We may want to find some time to meet and submit this resource. 

I think, as discussed during the summer, we would be submitting edav.info as is, and not modifying it to suit the contest. As stated in the contest blurb, you can submit a two-year old thesis if you want, so I think our resource is equally worth submitting.

I guess we could highlight:
- custom logo/chapter design
- easy-to-modify header and footers of every page
- custom return to top button
- external templates on publishing with bookdown
- lengthy tutorial on how to collaborate with bookdown
- open to other suggestions

**Comment by zachbogart** [comment]
- How you can contribute page
- Course companion 
- offset your coding examples/other materials that don't change between semesters
- remove tedium!
- open to everyone
- people can add to it as an assignment
- we still use courseworks/blackboard/etc for assignments and class-specific and scheduling

Is it useful for all semesters?

Sections: 
- need for course companion
- how to contribute: even technical students are anxious about contributing an issue, so we provide friendly and entertaining instructions to help out
- Instructions on making your own stuff

How you can contribute to OUR project and how you can do YOUR stuff.

**Comment by zachbogart** [comment]
I have a draft ready to go. We can find some time to meet next week and review it before submitting.

**Comment by jtr13** [comment]
Awesome. Do you want to email it to me to review before we meet? Thanks.

**Comment by zachbogart** [comment]
Sent you an invite to private repo

**Comment by zachbogart** [comment]
https://community.rstudio.com/t/bookdown-contest-submission-creating-a-course-companion-website-with-bookdown/15168

🎉
