### ISSUE TITLE
Update EDAV website 11.3 color session

### ISSUE THREAD

**Issue by shimengfeng** [jtr13/EDAV#95]
If I directly use Github, I understand that you will be able to review the change and approve it. However, will you be able to provide a certain level of instruction? The reason I ask this question is because that I am not a pro in color, but while I was doing hw1, I have found there are so much behind this topic, so I would like to dig more and add them on the website to make it more helpful. Thus, there might be things that are not perfect and a second-pair of eyes will be helpful.

**Comment by zachbogart** [comment]
Certainly! I will do my best to guide you in the right direction and we can discuss your additions and how they can best be presented. 

It sounds like you are interested in improving the [color/perception page](https://edav.info/percept.html). Before you get too far into overhauling the code, I'd appreciate an outline of what you plan on adding so we can work together to evolve the page. 

Looking forward to what you have planned. Thanks for helping improve edav.info.

**Comment by shimengfeng** [comment]
Hi Zach, 

Here are some of my thoughts before I start. There are two main goals for the overall enhancement: 

1. Basic instructions on how to embed color in ggplot2/tidyverse and what are the options/packages exist. These could be completed by leverage the additional resources online, such as: 
https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html
http://www.sthda.com/english/wiki/the-elements-of-choosing-colors-for-great-data-visualization-in-r

2. The importance of color affecting decision making and reader's response. I understand that the point is not to just make the graph pretty but to better visualization and convey the proper information. One of the most simple examples will be considering people link green color as correct and red color as wrong. Thus having different color coding will affect people's judgment. 

I am thinking the best way to show these is to choose several cases and use different representations to show how misleading data could get. I am checking what are some good examples, so please let me know if there is any source you know of. 

Please let me know if there is anything else that you could think of that I have missed, and I am more than happy to add on more.

**Comment by zachbogart** [comment]
I think the best addition would be color resources and explanations for why they are useful. The current page is color-coded yellow, meaning it is supposed to be pretty bare bones with just resources and brief explanations.

**Comment by jtr13** [comment]
If it interests you, I would suggest adding information about color vision deficiency - friendly colors, and how to check that the colors one uses are visible to someone with color vision deficiency (color blindness).

**Comment by shimengfeng** [comment]
@zachbogart Do you think it is possible to move it to a different color than a yellow page if I start to put some graph examples?  I have seen some basic code added, will it make sense to make a cheat sheet for color if that is the case?

**Comment by zachbogart** [comment]
Your choice.

**Comment by shimengfeng** [comment]
Hi Zach, 

I end up making this Rmarkdown file with other information, since I felt the page was originally designed as yellow and the information I would like to include here is much more. I have load a copy of my file with pizza, if you like any of the parts, I could add them later on to EDAV.com.
