### ISSUE TITLE
Add instructions for knitting to PDF

### ISSUE THREAD

**Issue by jtr13** [jtr13/EDAV#97]
Where appropriate, please add instructions on what needs to be downloaded and installed in order to be able to knit to PDF. Of course a link to a good online resource is fine, RStudio likely has something.

**Comment by zachbogart** [comment]
Beefed up the R Markdown section which references Knitr, but now is more prominent. 

https://edav.info/basics.html#r-markdown-knitr

Also, found that Travis needs to be on for pushed branches since I want master to be rendered if pushed directly. Could switch off if we choose to do everything thru pull requests.

**Comment by jtr13** [comment]
It looks like we can specify the branches to be built (i.e. master only) in the travis.yml file.  See "Building Specific Branches" here: https://docs.travis-ci.com/user/customizing-the-build/

```
# safelist
branches:
  only:
  - master
```

**Comment by jtr13** [comment]
Also, regarding the first issue, please add a section (or whatever is appropriate) that clearly mentions knitting to PDF. For reasons that have to do with CourseWorks, I'm requiring that homework be submitted as pdf files.  We need instructions that not only mention output: pdf_document but explain what needs to be installed before that will work.  Once it's up, I'll link to edav.info in the homework assignment.

**Comment by zachbogart** [comment]
I will look into testing the safelist for Travis as you described.

In regards to a section on submitting assignments, do you also want them to submit their Rmd file that generated the pdf? I remember last year we submitted both Rmd and html. I'm wondering in structuring my explanation of submitting their materials. Thanks.

**Comment by jtr13** [comment]
Yes, we've changed it since last year since the pdf's are easier to grade on CourseWorks. Thanks!

**Comment by zachbogart** [comment]
Also, I tried the Travis safelist and I'm not seeing any change. May have to try another way.

**Comment by jtr13** [comment]
They turn in .pdf and .Rmd but that doesn't need to go into edav.info since it could change... that's more a CourseWorks thing.

**Comment by jtr13** [comment]
Yes, fantastic, I already found it and linked to it in the homework assignment before your comment...
