### ISSUE TITLE
Add Walkthrough Page on a Homework Problem

### ISSUE THREAD

**Issue by zachbogart** [jtr13/EDAV#99]
In office hours, I had a great discussion of how to approach graphing a visualization that is complicated and involves some quirks with the data. Am thinking of adapting it into a walkthrough, explaining how to approach the problem and the final result.

I of course will not post it before the homework is due, but I think it would be an interesting long-term resource for people.

Let me know if you are comfortable with me using one of your homework questions as a full-fledged example in a walkthrough page. Thanks.

**Comment by jtr13** [comment]
Of course! We can use it too in the solutions. We can also use old homework questions for future walkthroughs since I don't reuse questions.

**Comment by zachbogart** [comment]
What walkthrough subject did you have in mind? Please clarify.

**Comment by rajbiswas** [comment]
I was thinking of doing one for Maps. Or should I add it as a chart in the Documentation (green section)? If you suggest the latter, should I create an issue and start working on it?
